    # -*- mode: ruby -*-
    # vi: set ft=ruby :
     
    Vagrant.configure("2") do |config|
     
        config.vm.box = "ubuntu/trusty64"
     
        config.vm.define :lamp do |lamp_config|
            lamp_config.vm.hostname = 'lamp'
            lamp_config.vm.network "private_network", ip: "192.168.50.10"
        end
        config.vm.provider :virtualbox do |vb_config|
            vb_config.name = "Vagrant - Ubuntu 14.04 LAMP"
        end
     
    end