version: '3.6'

services:

  vault:
    build:
      context: ./consul
      dockerfile: Dockerfile
    ports:
      - 8300:8300
      - 8400:8400
      - 8500:8500
      - 8600:8600              
    volumes:
      - ./consul/config:/consul/config
    command: agent -dev -bind 0.0.0.0 -client 0.0.0.0 -config-dir /consul/config/
    cap_add:
      - IPC_LOCK