version: '3'

services:

  consul-agent-1: &consul-agent
    image: consul:latest
    networks:
      - consul-demo
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    <<: *consul-agent


  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"


  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 2 -ui -client 0.0.0.0"

  vault:
    build:
      context: ./vault
      dockerfile: Dockerfile
    networks:
      - consul-demo
    ports:
      - 8200:8200
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    command: server -config=/vault/config/vault-config.json
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul-server-1
      - consul-server-bootstrap


  nomad1:
    build:
      context: ./nomaddir
      dockerfile: Dockerfile
    networks:
      - consul-demo
    ports:
      - 4646:4646
      - 4647:4647
      - 4648:4648
    volumes:
      - ./nomaddir:/nomaddir
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    command: agent -dev -config=/nomaddir/config/server.conf
    depends_on:
      - vault
      - consul-server-1

networks:
  consul-demo: